config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
  root 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    if @flat.save
      redirect_to flat_path(@flat)
    else
      @flat.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: 'Flat was successfully deleted.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
 <div class="container">
  <div class="flat">
 <%= simple_form_for(@flat) do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :img_url %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-primary" %>
  </div>
<% end %>
</div>
<div class="links">

 <p><%= link_to flats_path do %>
  <i class="fas fa-backward">Back</i>
  <% end %>
  </p>
  </div>
  </div>

app/views/flats/index.html.erb
<h1>All Flats</h1>
  <div class="container">
      <% @flats.each do |flat| %>
        <div class="cards">
          <div class="flat">
              <div class="card-img"><img src="<%= flat.img_url %>"></div>
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><i class="fas fa-map-marker-alt"> <em><%= flat.address %></em></i></p>
              <p class="card-text"><%= flat.description %></p>
              <p class="card-text"><i class="fas fa-user-friends"> <%= flat.number_of_guests %></i> - <i class="fas fa-moon"> <%= flat.price_per_night %>€</i></p>
              <p class="card-link">
                <div class= "links">
                  <div class="info">
                    <%= link_to flat_path(flat) do%>
                      <i class="fas fa-info">More info</i>
                    <% end %>
                  </div>
                  <div class="info">
                    <%= link_to edit_flat_path(flat) do %>
                      <i class="far fa-edit">Edit</i>
                    <% end %>
                  </div>
                    <div class="info">
                    <%= link_to flat_path(flat), method: :delete, data: { confirm: "Are you sure?" } do %>
                      <i class='far fa-trash-alt'>Delete</i>
                    <% end %>
                  </div>
                </div>
              </p>
            </div>
          </div>
      <% end %>
    </div>
  <br>
  <p><%= link_to new_flat_path do %>
  <i class="fas fa-plus"> Add a new flat</i>
  <% end %>
  </p>

app/views/flats/new.html.erb
<div class="container">
  <div class="flat">
 <%= simple_form_for(@flat) do |f| %>
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :img_url %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-primary" %>
  </div>
<% end %>
</div>
<div class="links">

 <p><%= link_to flats_path do %>
  <i class="fas fa-backward">Back</i>
  <% end %>
  </p>
  </div>
  </div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<div class="container">
  <div class="flat">
    <img src="<%= @flat.img_url %>">
    <p><%= @flat.description %></p>
    <p>Location: <%= @flat.address %> </p>
    <p>Number of Guests: <%= @flat.number_of_guests %> </p>
    <p>Price per night: <%= @flat.price_per_night %>€</p>

  </div>
  <div class="links">
  <p><%= link_to edit_flat_path(@flat) do %>
  <i class="far fa-edit">Edit</i>
  <% end %>
  </p>
  <p><%= link_to flat_path(@flat), method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class='far fa-trash-alt'>Delete</i>
                <% end %></p>
  <p><%= link_to flats_path do %>
  <i class="fas fa-backward">Back</i>
  <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">FlatB&B by Marie</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <a href="/flats/new">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Add a flat</button></a>
      </div>
    </nav>
    <div class="container bg-light">
    <%= yield %>
    </div>
  </body>
</html>